name: Action Workflow
on:
  - push
  - pull_request
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1
      - name: List after Checkout
        run: |
          pwd
          ls -a
      - name: JS Action
        id: greet
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: Marcio Marques de Souza
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}"
